/* USER */

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[ID_USER] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](255) NOT NULL,
	[LAST_NAME] [varchar](255) NOT NULL,
	[EMAIL] [varchar](255) NOT NULL,
	[PASSWORD] [varchar](255) NOT NULL,
	[ID_AGENCY] [int] NOT NULL,
	[DESCRIPTION] [varchar](255) NULL,
	CONSTRAINT [UQ_codes] UNIQUE NONCLUSTERED
(
    [EMAIL]
),
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID_USER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/* AGENCY */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AGENCY](
	[ID_AGENCY] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](255) NOT NULL,
	[LATITUDE] [decimal](9,6) NOT NULL,
	[LONGITUDE] [decimal](9,6) NOT NULL,
 CONSTRAINT [PK_AGENCY] PRIMARY KEY CLUSTERED 
(
	[ID_AGENCY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_AGENCY] FOREIGN KEY([ID_AGENCY])
REFERENCES [dbo].[AGENCY] ([ID_AGENCY])

INSERT [dbo].[AGENCY] ([NAME], [LATITUDE], [LONGITUDE]) VALUES ('INSA de Lyon', 45.78264, 4.878073)

INSERT [dbo].[USER] ([FIRST_NAME], [LAST_NAME], [EMAIL], [PASSWORD], [ID_AGENCY], [DESCRIPTION]) VALUES ('Terces', 'Connext', 'terces.connext@hardis.fr', 'password', 1, 'Test User')

INSERT [dbo].[USER] ([FIRST_NAME], [LAST_NAME], [EMAIL], [PASSWORD], [ID_AGENCY], [DESCRIPTION]) VALUES ('Marine', 'Martin', 'marine.martin@insa-lyon.fr', '5f4dcc3b5aa765d61d8327deb882cf99', 1, 'Test User')

INSERT [dbo].[USER] ([FIRST_NAME], [LAST_NAME], [EMAIL], [PASSWORD], [ID_AGENCY], [DESCRIPTION]) VALUES ('Maha', 'Benabbou', 'maha.benabbou@insa-lyon.fr', '5f4dcc3b5aa765d61d8327deb882cf99', 1, 'Test User')

INSERT [dbo].[USER] ([FIRST_NAME], [LAST_NAME], [EMAIL], [PASSWORD], [ID_AGENCY], [DESCRIPTION]) VALUES ('Hassan', 'El Moutaraji', 'hassan.el-moutaraji@insa-lyon.fr', '5f4dcc3b5aa765d61d8327deb882cf99', 1, 'Test User')

INSERT [dbo].[USER] ([FIRST_NAME], [LAST_NAME], [EMAIL], [PASSWORD], [ID_AGENCY], [DESCRIPTION]) VALUES ('Test1', 'Test', 'test1.test@test.com', '5f4dcc3b5aa765d61d8327deb882cf99', 1, 'Test User')

INSERT [dbo].[USER] ([FIRST_NAME], [LAST_NAME], [EMAIL], [PASSWORD], [ID_AGENCY], [DESCRIPTION]) VALUES ('Test2', 'Test', 'test2.test@test.com', '5f4dcc3b5aa765d61d8327deb882cf99', 1, 'Test User')

INSERT [dbo].[USER] ([FIRST_NAME], [LAST_NAME], [EMAIL], [PASSWORD], [ID_AGENCY], [DESCRIPTION]) VALUES ('Test3', 'Test', 'test3.test@test.com', '5f4dcc3b5aa765d61d8327deb882cf99', 1, 'Test User')


INSERT [dbo].[AGENCY] ([NAME], [LATITUDE], [LONGITUDE]) VALUES ('Université Lumière Lyon-II', 45.74921, 4.836951)

/* GROUP */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP](
	[ID_GROUP] [int] IDENTITY(1,1) NOT NULL,
	[LABEL] [varchar](255) NOT NULL,
 CONSTRAINT [PK_GROUP] PRIMARY KEY CLUSTERED 
(
	[ID_GROUP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

INSERT [dbo].[GROUP] ([LABEL]) VALUES ('Public')

INSERT [dbo].[GROUP] ([LABEL]) VALUES ('Hexanome')


/* USER GROUP */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_GROUP](
	[ID_USER] [int] NOT NULL,
	[ID_GROUP] [int] NOT NULL,
 CONSTRAINT [PK_USER_GROUP] PRIMARY KEY ([ID_USER],[ID_GROUP])
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[USER_GROUP]  WITH CHECK ADD  CONSTRAINT [FK_USERGROUP_USER] FOREIGN KEY([ID_USER])
REFERENCES [dbo].[USER] ([ID_USER])

GO
ALTER TABLE [dbo].[USER_GROUP]  WITH CHECK ADD  CONSTRAINT [FK_USERGROUP_GROUP] FOREIGN KEY([ID_GROUP])
REFERENCES [dbo].[GROUP] ([ID_GROUP])

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 1, 1)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 2, 1)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 3, 1)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 4, 1)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 5, 1)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 6, 1)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 7, 1)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 1, 2)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 2, 2)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 3, 2)

INSERT [dbo].[USER_GROUP] ([ID_USER], [ID_GROUP]) VALUES ( 4, 2)

/* CATEGORY */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORY](
	[ID_CATEGORY] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar] (255) NOT NULL,
	[DESCRIPTION] [varchar] (255),
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID_CATEGORY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


INSERT [dbo].[CATEGORY] ([TITLE], [DESCRIPTION]) VALUES ( 'Covoiturage', 'Trajet en voiture à plusieurs')

/* PUBLICATION */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLICATION](
	[ID_PUBLICATION] [int] IDENTITY(1,1) NOT NULL,
	[ID_USER] [int] NOT NULL,
	[TITLE] [varchar] (255) NOT NULL,
	[DESCRIPTION] [varchar] (255),
	[ID_CATEGORY] [int] NOT NULL,
	[ID_GROUP] [int] NOT NULL,
 CONSTRAINT [PK_PUBLICATION] PRIMARY KEY CLUSTERED 
(
	[ID_PUBLICATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [dbo].[PUBLICATION]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_CATEGORIE] FOREIGN KEY([ID_CATEGORY])
REFERENCES [dbo].[CATEGORY] ([ID_CATEGORY])

GO
ALTER TABLE [dbo].[PUBLICATION]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_USER] FOREIGN KEY([ID_USER])
REFERENCES [dbo].[USER] ([ID_USER])

GO
ALTER TABLE [dbo].[PUBLICATION]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_GROUP] FOREIGN KEY([ID_GROUP])
REFERENCES [dbo].[GROUP] ([ID_GROUP])

INSERT [dbo].[PUBLICATION] ([ID_USER], [TITLE], [DESCRIPTION], [ID_CATEGORY], [ID_GROUP]) VALUES (1, 'Covoiturage vers Lyon', 'Trajet en voiture à plusieurs', 1, 1)

/* TRAVEL */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRAVEL](
	[ID_TRAVEL] [int] IDENTITY(1,1) NOT NULL,
	[ID_DEPARTUREAGENCY] [int] NOT NULL,
	[ID_ARRIVALAGENCY] [int] NOT NULL,
	[CAPACITY] [int] NOT NULL,
	[DEPARTUREHOUR] [datetime] NOT NULL,
	[ARRIVALHOUR] [datetime] NOT NULL,
	[ID_PUBLICATION] [int] NOT NULL,
 CONSTRAINT [PK_TRAVEL] PRIMARY KEY CLUSTERED 
(
	[ID_TRAVEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[TRAVEL]  WITH CHECK ADD  CONSTRAINT [FK_TRAVEL_DEPARTUREAGENCY] FOREIGN KEY([ID_DEPARTUREAGENCY])
REFERENCES [dbo].[AGENCY] ([ID_AGENCY])

GO
ALTER TABLE [dbo].[TRAVEL]  WITH CHECK ADD  CONSTRAINT [FK_TRAVEL_ARRIVALAGENCY] FOREIGN KEY([ID_ARRIVALAGENCY])
REFERENCES [dbo].[AGENCY] ([ID_AGENCY])


GO
ALTER TABLE [dbo].[TRAVEL]  WITH CHECK ADD  CONSTRAINT [FK_TRAVEL_PUBLICATION] FOREIGN KEY([ID_PUBLICATION])
REFERENCES [dbo].[PUBLICATION] ([ID_PUBLICATION])

INSERT [dbo].[TRAVEL] ([ID_DEPARTUREAGENCY], [ID_ARRIVALAGENCY], [CAPACITY], [DEPARTUREHOUR], [ARRIVALHOUR], [ID_PUBLICATION]) VALUES (1, 2, 4, '2015-12-06 12:30:00', '2015-12-07 15:30:00', 1)

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACTION](
	[ID_ACTION] [int] IDENTITY(1,1) NOT NULL,
	[LIBELLE] [varchar] (10) NOT NULL,
 CONSTRAINT [PK_ACTION] PRIMARY KEY CLUSTERED 
(
	[ID_ACTION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


INSERT [dbo].[ACTION] ([LIBELLE]) VALUES ('AWAIT')
INSERT [dbo].[ACTION] ([LIBELLE]) VALUES ('ACCEPT')
INSERT [dbo].[ACTION] ([LIBELLE]) VALUES ('REJECT')

/* REQUEST TRAVEL */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REQUEST_TRAVEL](
	[ID_REQUEST_TRAVEL] [int] IDENTITY(1,1) NOT NULL,
	[ID_TRAVEL] [int] NOT NULL,
	[ID_USER] [int] NOT NULL,
	[ID_ACTION] [int] NOT NULL,
 CONSTRAINT [PK_REQUESTTRAVEL] PRIMARY KEY CLUSTERED 
(
	[ID_REQUEST_TRAVEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[REQUEST_TRAVEL]  WITH CHECK ADD  CONSTRAINT [FK_REQUESTTRAVEL_USER] FOREIGN KEY([ID_USER])
REFERENCES [dbo].[USER] ([ID_USER])

GO
ALTER TABLE [dbo].[REQUEST_TRAVEL]  WITH CHECK ADD  CONSTRAINT [FK_REQUESTTRAVEL_TRAVEL] FOREIGN KEY([ID_TRAVEL])
REFERENCES [dbo].[TRAVEL] ([ID_TRAVEL])

GO
ALTER TABLE [dbo].[REQUEST_TRAVEL]  WITH CHECK ADD  CONSTRAINT [FK_REQUESTTRAVEL_ACTION] FOREIGN KEY([ID_ACTION])
REFERENCES [dbo].[ACTION] ([ID_ACTION])

INSERT [dbo].[REQUEST_TRAVEL] ([ID_TRAVEL], [ID_USER], [ID_ACTION]) VALUES ( 1, 2, 1)

INSERT [dbo].[REQUEST_TRAVEL] ([ID_TRAVEL], [ID_USER], [ID_ACTION]) VALUES ( 1, 3, 2)

INSERT [dbo].[REQUEST_TRAVEL] ([ID_TRAVEL], [ID_USER], [ID_ACTION]) VALUES ( 1, 4, 2)


/* USER TOKEN*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SESSION](
	[ID_SESSION] [int] IDENTITY(1,1) NOT NULL,
	[ID_USER] [int] NOT NULL,
	[TOKEN] [uniqueidentifier] NOT NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[LAST_CONNECT_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_SESSION] PRIMARY KEY CLUSTERED 
(
	[ID_SESSION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[SESSION]  WITH CHECK ADD  CONSTRAINT [FK_SESSION_USER] FOREIGN KEY([ID_USER])
REFERENCES [dbo].[USER] ([ID_USER])


ALTER TABLE [dbo].[PUBLICATION]  
ADD [DATE_TIME_CREATION] [datetime] NOT NULL
CONSTRAINT PK_DATE_TIME DEFAULT GETDATE();