/* USER */

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[ID_USER] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](255) NOT NULL,
	[LAST_NAME] [varchar](255) NOT NULL,
	[EMAIL] [varchar](255) NOT NULL,
	[PASSWORD] [varchar](255) NOT NULL,
	[ID_AGENCY] [int] NOT NULL,
	[DESCRIPTION] [varchar](255) NULL,
	CONSTRAINT [UQ_codes] UNIQUE NONCLUSTERED
(
    [EMAIL]
),
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID_USER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/* AGENCY */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AGENCY](
	[ID_AGENCY] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](255) NOT NULL,
	[LATITUDE] [decimal](9,6) NOT NULL,
	[LONGITUDE] [decimal](9,6) NOT NULL,
 CONSTRAINT [PK_AGENCY] PRIMARY KEY CLUSTERED 
(
	[ID_AGENCY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_AGENCY] FOREIGN KEY([ID_AGENCY])
REFERENCES [dbo].[AGENCY] ([ID_AGENCY])

INSERT [dbo].[AGENCY] ([NAME], [LATITUDE], [LONGITUDE]) VALUES ('INSA de Lyon', 45.78264, 4.878073)

INSERT [dbo].[USER] ([FIRST_NAME], [LAST_NAME], [EMAIL], [PASSWORD], [ID_AGENCY], [DESCRIPTION]) VALUES ('Terces', 'Connext', 'terces.connext@hardis.fr', 'password', 1, 'Test User')

/* TRAVEL */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRAVEL](
	[ID_TRAVEL] [int] IDENTITY(1,1) NOT NULL,
	[ID_DEPARTUREAGENCY] [int] IDENTITY(1,1) NOT NULL,
	[ID_ARRIVALAGENCY] [int] IDENTITY(1,1) NOT NULL,
	[CAPACITY] [int] NOT NULL,
	[DEPARTUREHOUR] [datetime] NOT NULL,
	[ARRIVALHOUR] [datetime] NOT NULL,
 CONSTRAINT [PK_TRAVEL] PRIMARY KEY CLUSTERED 
(
	[ID_TRAVEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[TRAVEL]  WITH CHECK ADD  CONSTRAINT [FK_TRAVEL_DEPARTUREAGENCY] FOREIGN KEY([ID_DEPARTUREAGENCY])
REFERENCES [dbo].[AGENCY] ([ID_AGENCY])

GO
ALTER TABLE [dbo].[TRAVEL]  WITH CHECK ADD  CONSTRAINT [FK_TRAVEL_ARRIVALAGENCY] FOREIGN KEY([ID_ARRIVALAGENCY])
REFERENCES [dbo].[AGENCY] ([ID_AGENCY])

INSERT [dbo].[TRAVEL] ([ID_DEPARTUREAGENCY], [ID_ARRIVALAGENCY], [CAPACITY], [DEPARTUREHOUR], [ARRIVALHOUR]) VALUES (1, 1, 4, '2015-12-06 12:30:00', '2015-12-07 15:30:00')
