//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnextBusinessLayer.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTION()
        {
            this.REQUEST_TRAVEL = new HashSet<REQUEST_TRAVEL>();
        }
    
        public int ID_ACTION { get; set; }
        public string LIBELLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_TRAVEL> REQUEST_TRAVEL { get; set; }
    }
}
