//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnextBusinessLayer.Bdd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class connext_dbEntities : DbContext
    {
        public connext_dbEntities()
            : base("name=connext_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTION> ACTIONs { get; set; }
        public virtual DbSet<AGENCY> AGENCies { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<GROUP> GROUPs { get; set; }
        public virtual DbSet<PUBLICATION> PUBLICATIONs { get; set; }
        public virtual DbSet<REQUEST_TRAVEL> REQUEST_TRAVEL { get; set; }
        public virtual DbSet<SESSION> SESSIONs { get; set; }
        public virtual DbSet<TRAVEL> TRAVELs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
