//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnextBusinessLayer.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBLICATION()
        {
            this.TRAVELs = new HashSet<TRAVEL>();
        }
    
        public int ID_PUBLICATION { get; set; }
        public int ID_USER { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public int ID_CATEGORY { get; set; }
        public int ID_GROUP { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual GROUP GROUP { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAVEL> TRAVELs { get; set; }
    }
}
