//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnextBusinessLayer.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_TRAVEL
    {
        public int ID_REQUEST_TRAVEL { get; set; }
        public int ID_TRAVEL { get; set; }
        public int ID_USER { get; set; }
        public int ID_ACTION { get; set; }
    
        public virtual ACTION ACTION { get; set; }
        public virtual TRAVEL TRAVEL { get; set; }
        public virtual USER USER { get; set; }
    }
}
