//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnextBusinessLayer.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION
    {
        public int ID_SESSION { get; set; }
        public int ID_USER { get; set; }
        public System.Guid TOKEN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime LAST_CONNECT_DATE { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
