//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnextBusinessLayer.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAVEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAVEL()
        {
            this.REQUEST_TRAVEL = new HashSet<REQUEST_TRAVEL>();
        }
    
        public int ID_TRAVEL { get; set; }
        public int ID_DEPARTUREAGENCY { get; set; }
        public int ID_ARRIVALAGENCY { get; set; }
        public int CAPACITY { get; set; }
        public System.DateTime DEPARTUREHOUR { get; set; }
        public System.DateTime ARRIVALHOUR { get; set; }
        public int ID_PUBLICATION { get; set; }
    
        public virtual AGENCY AGENCY { get; set; }
        public virtual AGENCY AGENCY1 { get; set; }
        public virtual PUBLICATION PUBLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_TRAVEL> REQUEST_TRAVEL { get; set; }
    }
}
